name: Naukri Automation

on:
  schedule:
    - cron: '12 21 * * *'   # Runs daily at 9:00 UTC
    - cron: '0 14 * * *'  # Runs daily at 14:00 UTC
    - cron: '0 19 * * *'  # Runs daily at 19:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1.2.0

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Naukri Automation
        env:
          NAUKRI_USERNAME: ${{ secrets.NAUKRI_USERNAME }}
          NAUKRI_PASSWORD: ${{ secrets.NAUKRI_PASSWORD }}
        run: |
          python naukri.py
