name: Naukri Automation

on:
  schedule:
    - cron: '10,20 12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1.2.0
        with:
          chrome-version: 1270653

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi

      - name: Install xvfb
        run: sudo apt-get install -y xvfb

      - name: Run Selenium tests with xvfb
        env:
          NAUKRI_USERNAME: ${{ secrets.NAUKRI_USERNAME }}
          NAUKRI_PASSWORD: ${{ secrets.NAUKRI_PASSWORD }}
        run: |
          export DISPLAY=:99
          Xvfb :99 -screen 0 1920x1080x24 &
          python3 naukri.py

      - name: Upload Screenshots
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: '*.png'
